services:
  postgres:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:17.4
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./utils/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - nw
  companies-microservice:
    container_name: ${SERVICE_NAME}
    image: ${SERVICE_NAME}:latest
    ports:
      - ${SERVICE_EXPOSED_PORT}:${SERVICE_EXPOSED_PORT}
    depends_on:
      postgres:
        condition: service_started
    networks:
      - nw

volumes:
  postgres-data:
    name: postgres-data

networks:
  nw:
    driver: bridge